// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IOTapi.Model;

public partial class Addresstype1
{
    public int Id { get; set; }

    public string Addresstype { get; set; }
}