// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IOTapi.Model;

public partial class DeviceUnit
{
    public int UnitId { get; set; }

    public string UnitName { get; set; }

    public string Remarks { get; set; }
}