// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IOTapi.Model;

public partial class DeviceInstallationDetail
{
    public string Name { get; set; }

    public string Temperature { get; set; }

    public string ShortName { get; set; }

    public string Remarks { get; set; }

    public string Addressline1 { get; set; }

    public string Addressline2 { get; set; }

    public string Region { get; set; }

    public string Zone { get; set; }

    public string Imie { get; set; }

    public string SoName { get; set; }

    public string Mobilenumber { get; set; }

    public string Email { get; set; }
}