// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IOTapi.Model;

public partial class UserLogin
{
    public int UserId { get; set; }

    public string UserFname { get; set; }

    public string UserLname { get; set; }

    public string Email { get; set; }

    public string MobileNo { get; set; }

    public DateTime? LoginDate { get; set; }

    public int? LoginId { get; set; }

    public int? EntityId { get; set; }
}